"""
Localization module for multi-language support
"""

from core.config_manager import get_general_settings
import logging

# Default language is English
_current_language = "en"

# Logger setup
logger = logging.getLogger(__name__)

# Translations dictionary
_translations = {
    # English translations
    "en": {
        # General UI elements
        "settings": "Settings",
        "save": "Save",
        "close": "Close",
        "cancel": "Cancel",
        "ok": "OK",
        "error": "Error",
        "warning": "Warning",
        "info": "Information",
        
        # Email related
        "email_settings": "Email Settings",
        "test_email": "Test Email Settings",
        "smtp_server": "SMTP Server",
        "port": "Port",
        "security": "Security",
        "sender_email": "Sender Email",
        "password": "Password",
        "remember_password": "Remember password",
        
        # Email template translations for English
        "email_test_subject": "NewsDigest - Test Email",
        "email_test_header": "NewsDigest Test Email",
        "email_test_content1": "This is a test email to verify your email configuration.",
        "email_test_content2": "If you receive this email, your email service is configured successfully!",
        "email_test_success": "Test email sent successfully",
        "email_test_failed": "Failed to send test email",
        "email_settings_incomplete": "Email settings incomplete, please configure SMTP server, email, and password",
        "digest_subtitle": "News Digest",
        "no_title": "No Title",
        "no_content": "No Content",
        "unknown_source": "Unknown Source",
        "source": "Source",
        "publish_time": "Published",
        "read_original": "Read Original",
        "digest_footer": """This email was automatically generated by NewsDigest.
News content is summarized from original sources. The opinions and views expressed in the content do not represent those of NewsDigest.
For the full article, please click the "Read Original" link.""",
        
        # AI settings
        "ai_settings": "AI Settings",
        "ai_provider": "AI Provider",
        "model": "Model",
        "api_key": "API Key",
        
        # General settings
        "general_settings": "General Settings",
        "app_behavior": "Application Behavior",
        "start_on_boot": "Start application on system startup",
        "minimize_to_tray": "Minimize to system tray when closed",
        "show_notifications": "Show notifications",
        "skip_processed": "Skip processed news articles (test feature)",
        "language": "Language",
        
        # Data management
        "data_management": "Data Management",
        "clear_cache": "Clear RSS News Cache",
        "clear_cache_desc": "Click the button to clear the cache of processed news, ensuring all RSS sources will be retrieved and processed again on next run",
        
        # Interest tags
        "interest_tags": "Interest Tags",
        "set_interests": "Set your interest tags that will be automatically applied when adding new RSS feeds",
        
        # Scheduler
        "schedule_settings": "Schedule Settings",
        "frequency": "Frequency",
        "time": "Time",
        "run_on_days": "Run on these days",
        "weekdays": "Weekdays",
        "weekends": "Weekends",
        "all_days": "All Days",
        "none": "None",
        "last_run": "Last run",
        "next_run": "Next run",
        "never": "Never",
        "not_scheduled": "Not scheduled",
        
        # Scheduler translations
        "schedule_group": "Schedule Settings",
        "every": "Every",
        "weeks": "week(s)",
        "run_on_days": "Run on these days:",
        "weekdays_btn": "Weekdays",
        "weekends_btn": "Weekends",
        "all_days_btn": "All Days",
        "no_days_btn": "None",
        "monday": "Monday",
        "tuesday": "Tuesday",
        "wednesday": "Wednesday",
        "thursday": "Thursday",
        "friday": "Friday",
        "saturday": "Saturday",
        "sunday": "Sunday",
        "save_schedule": "Save Schedule",
        "no_days_selected": "No Days Selected",
        "no_days_selected_warning": "You haven't selected any days for this task.",
        "no_days_selected_confirm": "The task will not run automatically. Is this what you want?",
        "last_run_never": "Last run: Never",
        "last_run_time": "Last run: {}",
        "last_run_unknown": "Last run: Unknown format",
        "next_run_not_scheduled": "Next run: Not scheduled",
        "next_run_no_days": "Next run: No days selected",
        "next_run_error": "Next run: Error calculating next run time",
        "next_run_time": "Next run: {} ({})",
        "time_format_days": "{} days, {} hours, {} minutes from now",
        "time_format_hours": "{} hours, {} minutes from now",
        "time_format_minutes": "{} minutes from now",
        
        # Messages
        "settings_saved": "Settings saved!",
        "restart_required": "The language setting has been changed. Please restart the application for the changes to take effect.",
        
        # MainWindow
        "rss_feeds": "RSS Feeds",
        "schedule": "Schedule",
        "recipients": "Recipients",
        "run_now": "Run Now",
        "running": "Running...",
        "no_task": "No Task",
        "no_task_selected": "No task selected or available.",
        "task_started": "Task Started",
        "task_started_message": "The task",
        "task_started_note": "This may take some time, especially if using AI filtering.\nYou can continue using the application while the task runs.",
        "task_error": "Task Error",
        "error_starting_task": "Error starting task",
        "schedule_updated": "Schedule Updated",
        "schedule_updated_message": "The schedule has been updated.",
        "tasks_scheduled": "task(s) have been scheduled.",
        "schedule_error": "Schedule Error",
        "error_reloading_tasks": "Error reloading tasks",
        "settings_error": "Settings Error",
        "error_opening_settings": "Error opening settings",
        
        # Settings Window
        "email": "Email",
        "ai": "AI",
        "smtp_server_settings": "SMTP Server Settings",
        "authentication_settings": "Authentication Settings",
        "ollama_settings": "Ollama Settings",
        "openai_settings": "OpenAI Settings",
        "ollama_host": "Ollama Host",
        "refresh": "Refresh",
        "general": "General",
        "test_feature": "Test Feature",
        "skip_processed_tooltip": "When enabled, the system will skip already processed news articles to avoid duplicate processing",
        "clear_cache_tooltip": "Clear all RSS news data stored in the database to retrieve and process feeds from scratch",
        "unsaved_changes": "Unsaved Changes",
        "save_changes_prompt": "You have unsaved changes. Do you want to save before closing?",
        "incomplete_info": "Incomplete Information",
        "fill_email_settings": "Please fill in all email settings (server, email, and password).",
        "sending_test": "Sending Test",
        "sending_test_to": "Sending test email to",
        "please_wait": "Please wait...",
        "success": "Success",
        "test_email_sent": "Test email sent successfully!",
        "failed": "Failed",
        "test_email_failed": "Failed to send test email.",
        "settings_effect_next_run": "New article processing settings will take effect on the next task run!",
        
        # Tag editor translations
        "add_tag_placeholder": "Add a tag...",
        "add": "Add",
        
        # Common tags
        "tag_news": "News",
        "tag_politics": "Politics",
        "tag_finance": "Finance",
        "tag_sports": "Sports",
        "tag_technology": "Technology",
        "tag_entertainment": "Entertainment",
        "tag_education": "Education",
        "tag_health": "Health",
        "tag_culture": "Culture",
        "tag_travel": "Travel",
        "tag_automotive": "Automotive",
        "tag_real_estate": "Real Estate",
        "tag_electronics": "Electronics",
        "tag_fashion": "Fashion",
        
        # Tray icon translations
        "show_window": "Show Window",
        "exit": "Exit",
        
        # Feed management
        "rss_feed_config": "RSS Feed Configuration",
        "rss_feed_url": "RSS Feed URL:",
        "items_to_fetch": "Number of news items to fetch:",
        "items": " items",  # Retain this one, remove the duplicate
        "rss_feeds_for_task": "RSS Feeds for this Task:",
        "feed_url": "Feed URL",
        "labels": "Labels",
        "status": "Status",
        "last_fetch_time": "Last Fetch Time",
        "move_feed_up": "Move feed up",
        "move_feed_down": "Move feed down",
        "add_feed": "Add Feed",
        "edit_feed": "Edit Feed",
        "remove_feed": "Remove Feed",
        "test_feed": "Test Feed",
        "never": "Never",
        "feed_test_success": "Successfully fetched feed: {}",
        "feed_test_failed": "Failed to fetch feed: {}",
        
        # Task management
        "add_task": "Add Task",
        "edit_task": "Edit Task",
        "remove_task": "Remove Task",
        "new_task": "New Task",
        "enter_task_name": "Enter task name:",
        "enter_new_task_name": "Enter new task name:",
        "task_name_exists": "A task with this name already exists.",
        "confirm_delete": "Confirm Delete",
        "confirm_delete_task": "Are you sure you want to delete task '{}'?",
        "duplicate_task": "Duplicate Task",
        "enter_duplicate_task_name": "Enter name for the duplicate task:",
        "copy": "Copy",
        "cannot_delete": "Cannot Delete",
        "cannot_delete_only_task": "Cannot delete the only task. At least one task must remain.",
        "select_task": "Select Task:",
        "task_duplicated": "Task Duplicated",
        "task_duplicated_message": "Task has been duplicated as '{}'",
        "loaded_tasks": "Loaded {} tasks",
        "selected_first_task": "Selected first task: {}",
        "no_tasks_found": "No tasks found, creating default task",
        "error_loading_tasks": "Error loading tasks: {}",
        "error_updating_task_list": "Error updating task list: {}",
        "default_task": "Default Task",
        
        # Add new translations for RecipientManager
        "email_recipients": "Email Recipients",
        "email_address": "Email Address",
        "last_sent_time": "Last Sent Time",
        "add_recipient": "Add Recipient",
        "remove_recipient": "Remove Recipient",
        "enter_email_address": "Enter email address:",
        "invalid_format": "Invalid format",
        "email_test": "Email Test",
        "test_email_success": "Successfully sent test email to: {}",
        "test_email_failed": "Failed to send test email to: {}",
    },
    
    # Chinese translations
    "zh": {
        # General UI elements
        "settings": "设置",
        "save": "保存",
        "close": "关闭",
        "cancel": "取消",
        "ok": "确定",
        "error": "错误",
        "warning": "警告",
        "info": "信息",
        
        # Email related
        "email_settings": "邮箱设置",
        "test_email": "测试邮箱设置",
        "smtp_server": "SMTP服务器",
        "port": "端口",
        "security": "安全类型",
        "sender_email": "发件人邮箱",
        "password": "密码",
        "remember_password": "记住密码",
        
        # Email template translations for Chinese
        "email_test_subject": "NewsDigest - 测试邮件",
        "email_test_header": "NewsDigest 测试邮件",
        "email_test_content1": "这是一封测试邮件，用于验证您的邮件配置。",
        "email_test_content2": "如果您收到这封邮件，说明您的邮件服务配置成功！",
        "email_test_success": "测试邮件发送成功",
        "email_test_failed": "发送测试邮件失败",
        "email_settings_incomplete": "邮件设置不完整，请配置SMTP服务器、邮箱和密码",
        "digest_subtitle": "新闻简报",
        "no_title": "无标题",
        "no_content": "无内容",
        "unknown_source": "未知来源",
        "source": "来源",
        "publish_time": "发布时间",
        "read_original": "阅读原文",
        "digest_footer": """此邮件由NewsDigest自动生成。
新闻内容均总结自原文，观点和立场不代表NewsDigest。
如需阅读完整文章，请点击"阅读原文"链接。""",
        
        # AI settings
        "ai_settings": "AI设置",
        "ai_provider": "AI提供商",
        "model": "模型",
        "api_key": "API密钥",
        
        # General settings
        "general_settings": "常规设置",
        "app_behavior": "应用程序行为",
        "start_on_boot": "系统启动时运行应用程序",
        "minimize_to_tray": "关闭时最小化到系统托盘",
        "show_notifications": "显示通知",
        "skip_processed": "跳过已处理的新闻文章（测试功能）",
        "language": "语言",
        
        # Data management
        "data_management": "数据管理",
        "clear_cache": "清除RSS新闻缓存",
        "clear_cache_desc": "点击按钮清除已处理的新闻缓存，确保下次运行时重新获取和处理所有RSS源",
        
        # Interest tags
        "interest_tags": "兴趣标签",
        "set_interests": "设置您的兴趣标签，添加新RSS源时将自动应用",
        
        # Scheduler
        "schedule_settings": "定时设置",
        "frequency": "频率",
        "time": "时间",
        "run_on_days": "在这些日子运行",
        "weekdays": "工作日",
        "weekends": "周末",
        "all_days": "所有日子",
        "none": "无",
        "last_run": "上次运行",
        "next_run": "下次运行",
        "never": "从未",
        "not_scheduled": "未定时",
        
        # Scheduler translations
        "schedule_group": "定时设置",
        "every": "每",
        "weeks": "周",
        "run_on_days": "在这些天运行：",
        "weekdays_btn": "工作日",
        "weekends_btn": "周末",
        "all_days_btn": "每天",
        "no_days_btn": "无",
        "monday": "星期一",
        "tuesday": "星期二",
        "wednesday": "星期三",
        "thursday": "星期四",
        "friday": "星期五",
        "saturday": "星期六",
        "sunday": "星期日",
        "save_schedule": "保存定时",
        "no_days_selected": "未选择日期",
        "no_days_selected_warning": "您尚未为此任务选择任何日期。",
        "no_days_selected_confirm": "任务将不会自动运行。确定要这样设置吗？",
        "last_run_never": "上次运行：从未",
        "last_run_time": "上次运行：{}",
        "last_run_unknown": "上次运行：未知格式",
        "next_run_not_scheduled": "下次运行：未定时",
        "next_run_no_days": "下次运行：未选择日期",
        "next_run_error": "下次运行：计算下次运行时间出错",
        "next_run_time": "下次运行：{} ({})",
        "time_format_days": "{}天{}小时{}分钟后",
        "time_format_hours": "{}小时{}分钟后",
        "time_format_minutes": "{}分钟后",
        
        # Messages
        "settings_saved": "设置已保存！",
        "restart_required": "语言设置已更改。请重新启动应用程序以使更改生效。",
        
        # MainWindow
        "rss_feeds": "RSS源",
        "schedule": "定时",
        "recipients": "接收者",
        "run_now": "立即运行",
        "running": "正在运行...",
        "no_task": "无任务",
        "no_task_selected": "没有选择或可用的任务。",
        "task_started": "任务已启动",
        "task_started_message": "任务",
        "task_started_note": "这可能需要一些时间，特别是使用AI过滤时。\n您可以在任务运行时继续使用应用程序。",
        "task_error": "任务错误",
        "error_starting_task": "启动任务出错",
        "schedule_updated": "定时已更新",
        "schedule_updated_message": "定时已更新。",
        "tasks_scheduled": "个任务已被定时。",
        "schedule_error": "定时错误",
        "error_reloading_tasks": "重新加载任务出错",
        "settings_error": "设置错误",
        "error_opening_settings": "打开设置出错",
        
        # Settings Window
        "email": "邮箱",
        "ai": "AI",
        "smtp_server_settings": "SMTP服务器设置",
        "authentication_settings": "认证设置",
        "ollama_settings": "Ollama设置",
        "openai_settings": "OpenAI设置",
        "ollama_host": "Ollama主机",
        "refresh": "刷新",
        "general": "常规",
        "test_feature": "测试功能",
        "skip_processed_tooltip": "启用后，系统将跳过已处理过的新闻文章，避免重复处理",
        "clear_cache_tooltip": "清除数据库中存储的所有RSS新闻数据，以便重新获取和处理",
        "unsaved_changes": "未保存的更改",
        "save_changes_prompt": "您有未保存的更改。是否在关闭前保存？",
        "incomplete_info": "信息不完整",
        "fill_email_settings": "请填写所有邮箱设置（服务器、邮箱和密码）。",
        "sending_test": "发送测试",
        "sending_test_to": "正在发送测试邮件到",
        "please_wait": "请稍候...",
        "success": "成功",
        "test_email_sent": "测试邮件发送成功！",
        "failed": "失败",
        "test_email_failed": "发送测试邮件失败。",
        "settings_effect_next_run": "新的文章处理设置将在下次运行任务时生效！",
        
        # Tag editor translations
        "add_tag_placeholder": "添加标签...",
        "add": "添加",
        
        # Common tags
        "tag_news": "新闻",
        "tag_politics": "政治",
        "tag_finance": "财经",
        "tag_sports": "体育",
        "tag_technology": "科技",
        "tag_entertainment": "娱乐",
        "tag_education": "教育",
        "tag_health": "健康",
        "tag_culture": "文化",
        "tag_travel": "旅游",
        "tag_automotive": "汽车",
        "tag_real_estate": "房地产",
        "tag_electronics": "电子",
        "tag_fashion": "时尚",
        
        # Tray icon translations
        "show_window": "显示窗口",
        "exit": "退出",
        
        # Feed management
        "rss_feed_config": "RSS源配置",
        "rss_feed_url": "RSS源地址：",
        "items_to_fetch": "获取新闻条数：",
        "items": " 条",  # Retain this one, remove the duplicate
        "rss_feeds_for_task": "任务的RSS源：",
        "feed_url": "源地址",
        "labels": "标签",
        "status": "状态",
        "last_fetch_time": "最后获取时间",
        "move_feed_up": "上移源",
        "move_feed_down": "下移源",
        "add_feed": "添加源",
        "edit_feed": "编辑源",
        "remove_feed": "删除源",
        "test_feed": "测试源",
        "never": "从未",
        "feed_test_success": "成功获取源：{}",
        "feed_test_failed": "获取源失败：{}",
        
        # Task management
        "add_task": "添加任务",
        "edit_task": "编辑任务",
        "remove_task": "删除任务",
        "new_task": "新建任务",
        "enter_task_name": "输入任务名称：",
        "enter_new_task_name": "输入新的任务名称：",
        "task_name_exists": "已存在同名任务。",
        "confirm_delete": "确认删除",
        "confirm_delete_task": "确定要删除任务'{}'吗？",
        "duplicate_task": "复制任务",
        "enter_duplicate_task_name": "输入复制任务的名称：",
        "copy": "副本",
        "cannot_delete": "无法删除",
        "cannot_delete_only_task": "无法删除唯一的任务。必须保留至少一个任务。",
        "select_task": "选择任务：",
        "task_duplicated": "任务已复制",
        "task_duplicated_message": "任务已复制为'{}'",
        "loaded_tasks": "已加载 {} 个任务",
        "selected_first_task": "已选择第一个任务：{}",
        "no_tasks_found": "未找到任务，创建默认任务",
        "error_loading_tasks": "加载任务出错：{}",
        "error_updating_task_list": "更新任务列表出错：{}",
        "default_task": "默认任务",
        
        # Add Chinese translations for RecipientManager
        "email_recipients": "邮件接收者",
        "email_address": "邮箱地址",
        "last_sent_time": "最后发送时间",
        "add_recipient": "添加接收者",
        "remove_recipient": "删除接收者",
        "enter_email_address": "输入邮箱地址：",
        "invalid_format": "无效格式",
        "email_test": "邮件测试",
        "test_email_success": "成功发送测试邮件至：{}",
        "test_email_failed": "发送测试邮件失败：{}",
    }
}

def initialize():
    """Initialize localization system by loading current language from settings"""
    global _current_language
    settings = get_general_settings()
    _current_language = settings.get("language", "en")
    print(f"Localization initialized with language: {_current_language}")

def get_text(key):
    """Get translated text for the given key"""
    try:
        return _translations[_current_language].get(key, key)
    except KeyError:
        # Fallback to English if the language is not available
        try:
            return _translations["en"].get(key, key)
        except KeyError:
            # Return the key itself if it's not found in any language
            return key

def get_current_language():
    """Get the current language code"""
    logger.info(f"Current language requested: {_current_language}")
    return _current_language

def set_language(language_code):
    """Set the current language"""
    global _current_language
    if language_code in _translations:
        logger.info(f"Setting language from {_current_language} to {language_code}")
        _current_language = language_code
        return True
    logger.warning(f"Attempted to set invalid language: {language_code}")
    return False

# Helper function for text with parameters
def get_formatted(key, *args, **kwargs):
    """Get translated text and format it with the given parameters"""
    text = get_text(key)
    try:
        if args or kwargs:
            return text.format(*args, **kwargs)
        return text
    except Exception:
        # If formatting fails, return the unformatted text
        return text
